/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.43
 * Generated at: 2021-01-04 12:09:06 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.user;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import user.model.vo.User;
import user.model.vo.User;

public final class userUpdateView_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/views/user/../common/header.jsp", Long.valueOf(1609758860215L));
    _jspx_dependants.put("/views/user/../common/footer.jsp", Long.valueOf(1609658644552L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("user.model.vo.User");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('x');
      out.write('\r');
      out.write('\n');

	User user = (User)request.getAttribute("user");

	//주소(address)를 값을 각각의 문자열로 분리 처리
	String[] Address = user.getAddress().split(",");

      out.write("    \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>직산 가정의학 의원</title>\r\n");
      out.write("<script src=\"http://dmaps.daum.net/map_js_init/postcode.v2.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("\t//본 예제에서는 도로명 주소 표기 방식에 대한 법령에 따라, 내려오는 데이터를 조합하여 올바른 주소를 구성하는 방법을 설명합니다.\r\n");
      out.write("\tfunction sample4_execDaumPostcode() {\r\n");
      out.write("\t\tnew daum.Postcode(\r\n");
      out.write("\t\t\t\t{\r\n");
      out.write("\t\t\t\t\toncomplete : function(data) {\r\n");
      out.write("\t\t\t\t\t\t// 팝업에서 검색결과 항목을 클릭했을때 실행할 코드를 작성하는 부분.\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t// 도로명 주소의 노출 규칙에 따라 주소를 표시한다.\r\n");
      out.write("\t\t\t\t\t\t// 내려오는 변수가 값이 없는 경우엔 공백('')값을 가지므로, 이를 참고하여 분기 한다.\r\n");
      out.write("\t\t\t\t\t\tvar roadAddr = data.roadAddress; // 도로명 주소 변수\r\n");
      out.write("\t\t\t\t\t\tvar extraRoadAddr = ''; // 참고 항목 변수\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t// 법정동명이 있을 경우 추가한다. (법정리는 제외)\r\n");
      out.write("\t\t\t\t\t\t// 법정동의 경우 마지막 문자가 \"동/로/가\"로 끝난다.\r\n");
      out.write("\t\t\t\t\t\tif (data.bname !== '' && /[동|로|가]$/g.test(data.bname)) {\r\n");
      out.write("\t\t\t\t\t\t\textraRoadAddr += data.bname;\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t// 건물명이 있고, 공동주택일 경우 추가한다.\r\n");
      out.write("\t\t\t\t\t\tif (data.buildingName !== '' && data.apartment === 'Y') {\r\n");
      out.write("\t\t\t\t\t\t\textraRoadAddr += (extraRoadAddr !== '' ? ', '\r\n");
      out.write("\t\t\t\t\t\t\t\t\t+ data.buildingName : data.buildingName);\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t// 표시할 참고항목이 있을 경우, 괄호까지 추가한 최종 문자열을 만든다.\r\n");
      out.write("\t\t\t\t\t\tif (extraRoadAddr !== '') {\r\n");
      out.write("\t\t\t\t\t\t\textraRoadAddr = ' (' + extraRoadAddr + ')';\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t// 우편번호와 주소 정보를 해당 필드에 넣는다.\r\n");
      out.write("\t\t\t\t\t\tdocument.getElementById('sample4_postcode').value = data.zonecode;\r\n");
      out.write("\t\t\t\t\t\tdocument.getElementById(\"sample4_roadAddress\").value = roadAddr;\r\n");
      out.write("\t\t\t\t\t\tdocument.getElementById(\"sample4_jibunAddress\").value = data.jibunAddress;\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\tdocument.getElementById(\"sample4_engAddress\").value = data.addressEnglish;\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t// 참고항목 문자열이 있을 경우 해당 필드에 넣는다.\r\n");
      out.write("\t\t\t\t\t\tif (roadAddr !== '') {\r\n");
      out.write("\t\t\t\t\t\t\tdocument.getElementById(\"sample4_extraAddress\").value = extraRoadAddr;\r\n");
      out.write("\t\t\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t\t\tdocument.getElementById(\"sample4_extraAddress\").value = '';\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\tvar guideTextBox = document.getElementById(\"guide\");\r\n");
      out.write("\t\t\t\t\t\t// 사용자가 '선택 안함'을 클릭한 경우, 예상 주소라는 표시를 해준다.\r\n");
      out.write("\t\t\t\t\t\tif (data.autoRoadAddress) {\r\n");
      out.write("\t\t\t\t\t\t\tvar expRoadAddr = data.autoRoadAddress\r\n");
      out.write("\t\t\t\t\t\t\t\t\t+ extraRoadAddr;\r\n");
      out.write("\t\t\t\t\t\t\tguideTextBox.innerHTML = '(예상 도로명 주소 : '\r\n");
      out.write("\t\t\t\t\t\t\t\t\t+ expRoadAddr + ')';\r\n");
      out.write("\t\t\t\t\t\t\tguideTextBox.style.display = 'block';\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t} else if (data.autoJibunAddress) {\r\n");
      out.write("\t\t\t\t\t\t\tvar expJibunAddr = data.autoJibunAddress;\r\n");
      out.write("\t\t\t\t\t\t\tguideTextBox.innerHTML = '(예상 지번 주소 : '\r\n");
      out.write("\t\t\t\t\t\t\t\t\t+ expJibunAddr + ')';\r\n");
      out.write("\t\t\t\t\t\t\tguideTextBox.style.display = 'block';\r\n");
      out.write("\t\t\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t\t\tguideTextBox.innerHTML = '';\r\n");
      out.write("\t\t\t\t\t\t\tguideTextBox.style.display = 'none';\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}).open();\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write('\r');
      out.write('\n');

	User loginUser = (User)session.getAttribute("loginUser");

      out.write("    \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"/jiksan/resources/css/jiksan-header.css\"/>\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"/jiksan/resources/css/main_slick.css\"/>      ");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/jiksan/resources/css/main_bootstrap.min.css\">      ");
      out.write("\r\n");
      out.write("<link href=\"/jiksan/resources/css/main_reset.css\" rel=\"stylesheet\" type=\"text/css\" />      ");
      out.write("\r\n");
      out.write("<link href=\"/jiksan/resources/css/main_common.css\" rel=\"stylesheet\" type=\"text/css\" />      ");
      out.write("\r\n");
      out.write("<link href=\"/jiksan/resources/css/main_main.css\" rel=\"stylesheet\" type=\"text/css\" />      ");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script type = \"text/javascript\" src = \"/jiksan/resources/js/jquery-3.5.1.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("$(document).ready(function(){\r\n");
      out.write("   $(\".full-slide\").click(function() {\r\n");
      out.write("      $(\".full-menu\").stop().slideToggle(300);\r\n");
      out.write("         $('.hamburger .line').css('transition', 'all 0.2s ease-in-out');\r\n");
      out.write("\r\n");
      out.write("         if($('.hamburger').hasClass('is-active')){\r\n");
      out.write("            $('.hamburger span:nth-child(1)').css({'transform':'translateY(0) rotate(0)'});\r\n");
      out.write("            $('.hamburger span:nth-child(2)').css({'opacity':'1'});\r\n");
      out.write("            $('.hamburger span:nth-child(3)').css({'transform':'translateY(0) rotate(0)'});            \r\n");
      out.write("            $('.hamburger').removeClass('is-active');\r\n");
      out.write("         } else {\r\n");
      out.write("            $('.hamburger span:nth-child(1)').css({'transform':'translateY(12px) rotate(45deg)'});\r\n");
      out.write("            $('.hamburger span:nth-child(2)').css({'opacity':'0'});\r\n");
      out.write("            $('.hamburger span:nth-child(3)').css({'transform':'translateY(-4px) rotate(-45deg)'});\r\n");
      out.write("            $('.hamburger').addClass('is-active');\r\n");
      out.write("         }\r\n");
      out.write("    });\r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("   function setCookie(name, value, expiredays) {\r\n");
      out.write("      var todayDate = new Date();\r\n");
      out.write("      todayDate.setDate(todayDate.getDate() + expiredays);\r\n");
      out.write("      document.cookie = name + \"=\" + escape(value) + \"; path=/; expires=\" + todayDate.toGMTString() + \";\"\r\n");
      out.write("   }\r\n");
      out.write("   function getCookie(name) {\r\n");
      out.write("      var nameOfCookie = name + \"=\";\r\n");
      out.write("      var x = 0;\r\n");
      out.write("      while (x <= document.cookie.length) {\r\n");
      out.write("         var y = (x + nameOfCookie.length);\r\n");
      out.write("         if (document.cookie.substring(x, y) == nameOfCookie) {\r\n");
      out.write("            if ((endOfCookie = document.cookie.indexOf(\";\", y)) == -1)\r\n");
      out.write("               endOfCookie = document.cookie.length;\r\n");
      out.write("            return unescape(document.cookie.substring(y, endOfCookie));\r\n");
      out.write("         }\r\n");
      out.write("         x = document.cookie.indexOf(\" \", x) + 1;\r\n");
      out.write("         if (x == 0)\r\n");
      out.write("            break;\r\n");
      out.write("      }\r\n");
      out.write("      return \"\";\r\n");
      out.write("   }\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div id=\"wrap\" class=\"mw1600\" style=\"position:relative;\">\r\n");
      out.write("      <div class=\"mw1600\">\r\n");
      out.write("   <header class=\"bg-white mw\">\r\n");
      out.write("      <div id=\"header-wrap\" class=\"inner cf\">\r\n");
      out.write("         <a href=\"/jiksan/index.jsp\"><img src=\"/jiksan/resources/main_images/jiksan_logo.png\" alt=\"직산 가정의학과 의원\" style=\"width: auto; max-width: 22%\"></a>\r\n");
      out.write("\r\n");
      out.write("<section>\r\n");
      out.write('\r');
      out.write('\n');
 if(loginUser == null){ //로그인 안 했다면 
      out.write("\r\n");
      out.write("         <nav>\r\n");
      out.write("            <a href=\"/jiksan/views/user/userLogin.jsp\"><img src=\"/jiksan/resources/main_images/nav-icon01.png\" alt=\"LOGIN\"><span>LOGIN</span></a>\r\n");
      out.write("            <a href=\"/jiksan/views/user/userEnroll.jsp\"><img src=\"/jiksan/resources/main_images/nav-icon02.png\" alt=\"JOIN\"><span>JOIN</span></a>\r\n");
      out.write("            <a href=\"/jiksan/contact-us\"><img src=\"/jiksan/resources/main_images/nav-icon03.png\" alt=\"CONTACT US\"><span>CONTACT US</span></a>\r\n");
      out.write("            <a href=\"#n\" class=\"full-slide\">\r\n");
      out.write("               <div class=\"row\">\r\n");
      out.write("                  <div class=\"three col\">\r\n");
      out.write("                     <div class=\"hamburger\" id=\"hamburger-1\">\r\n");
      out.write("                        <span class=\"line\"></span>\r\n");
      out.write("                        <span class=\"line\"></span>\r\n");
      out.write("                        <span class=\"line\"></span>\r\n");
      out.write("                     </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("               </div>\r\n");
      out.write("               <span style=\"font-weight: 500; color: #74afc9;\">전체메뉴</span>\r\n");
      out.write("            </a>\r\n");
      out.write("         </nav>\r\n");
      out.write("         </div>\r\n");
      out.write("            <div class=\"full-menu bg-white\">\r\n");
      out.write("         <div class=\"inner\">\r\n");
      out.write("            <ul class=\"full-list inner cf\">\r\n");
      out.write("               <li>\r\n");
      out.write("                  <div>병원안내</div>\r\n");
      out.write("                  <ol>\r\n");
      out.write("                     <li><a href=\"/jiksan/about-clinic\">병원안내</a></li>\r\n");
      out.write("                     <li><a href=\"/jiksan/about-services\">진료안내</a></li>\r\n");
      out.write("                     <li><a href=\"/jiksan/about-team\">의료진 소개</a></li>\r\n");
      out.write("                            <li><a href=\"/jiksan/contact-us\">오시는길</a></li>\r\n");
      out.write("                  </ol>\r\n");
      out.write("               </li>\r\n");
      out.write("               <li>\r\n");
      out.write("                  <div>당뇨클리닉</div>\r\n");
      out.write("                  <ol>\r\n");
      out.write("                     <li><a href=\"/jiksan/diabetes\" >당뇨병이란?</a></li>\r\n");
      out.write("                     <li><a href=\"/jiksan/diabetes-test\" >당뇨병 검사</a></li>\r\n");
      out.write("                     <li><a href=\"/jiksan/diabetes-diet\" >당뇨병과 식생활</a></li>\r\n");
      out.write("                     <li><a href=\"/jiksan/diabetes-exercise\" >당뇨병과 운동</a></li>\r\n");
      out.write("                     <li><a href=\"/jiksan/diabetes-complications\" >당뇨병 합병증</a></li>\r\n");
      out.write("                  </ol>\r\n");
      out.write("               </li>\r\n");
      out.write("               <li>\r\n");
      out.write("                  <div>건강정보</div>\r\n");
      out.write("                  <ol>\r\n");
      out.write("                     <li><a href=\"/jiksan/about-disease\">질환백과</a></li>\r\n");
      out.write("                     ");
      out.write("\r\n");
      out.write("                  </ol>   \r\n");
      out.write("               </li>\r\n");
      out.write("               <li>\r\n");
      out.write("                  <div>진료 예약</div>\r\n");
      out.write("                  <ol>\r\n");
      out.write("                     <li><a href=\"#\">예약안내</a></li>\r\n");
      out.write("                     <li><a href=\"/jiksan/views/user/userReservation.html\">진료 예약하기</a></li>\r\n");
      out.write("                     ");
      out.write("\r\n");
      out.write("                  </ol>   \r\n");
      out.write("               </li>\r\n");
      out.write("               <li>\r\n");
      out.write("                  <div>커뮤니티</div>\r\n");
      out.write("                  <ol>\r\n");
      out.write("                     <li><a href=\"/jiksan/views/notice/nlist\">공지사항</a></li>\r\n");
      out.write("                     <li><a href=\"/jiksan/views/faq/faqlist\">자주묻는 질문</a></li>\r\n");
      out.write("                     <li><a href=\"#\">Q&A 게시판</a></li>\r\n");
      out.write("                     ");
      out.write("\r\n");
      out.write("                  </ol>   \r\n");
      out.write("               </li>\r\n");
      out.write("            </ul>\r\n");
      out.write("         </div>\r\n");
 } else if (loginUser != null && loginUser.getUserLv() >= 2){ 
      out.write(" <!-- 관리자가 로그인했다면 -->\r\n");
      out.write("\t\t<nav>\r\n");
      out.write("            <a href=\"/jiksan/logout\"><img src=\"/jiksan/resources/main_images/nav-icon01.png\" alt=\"LOGOUT\"><span>LOGOUT</span></a>\r\n");
      out.write("            <a href=\"/jiksan/views/user/userMyPage.jsp\"><img src=\"/jiksan/resources/main_images/nav-icon02.png\" alt=\"MY PAGE\"><span>MY PAGE</span></a>\r\n");
      out.write("            <a href=\"/jiksan/views/reservation/userReservation.html\"><img src=\"/jiksan/resources/main_images/nav-icon04.png\" alt=\"RESERVATION\"><span>RESERVATION</span></a>\r\n");
      out.write("            <a href=\"#n\" class=\"full-slide\">\r\n");
      out.write("               <div class=\"row\">\r\n");
      out.write("                  <div class=\"three col\">\r\n");
      out.write("                     <div class=\"hamburger\" id=\"hamburger-1\">\r\n");
      out.write("                        <span class=\"line\"></span>\r\n");
      out.write("                        <span class=\"line\"></span>\r\n");
      out.write("                        <span class=\"line\"></span>\r\n");
      out.write("                     </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("               </div>\r\n");
      out.write("               <span style=\"font-weight: 500; color: #74afc9;\">전체메뉴</span>\r\n");
      out.write("            </a>\r\n");
      out.write("         </nav>\r\n");
      out.write("      </div>\r\n");
      out.write("            <div class=\"full-menu bg-white\">\r\n");
      out.write("         <div class=\"inner\">\r\n");
      out.write("            <ul class=\"full-list inner cf\">\r\n");
      out.write("               <li>\r\n");
      out.write("                  <div>병원안내</div>\r\n");
      out.write("                  <ol>\r\n");
      out.write("                     <li><a href=\"/jiksan/about-clinic\">병원안내</a></li>\r\n");
      out.write("                     <li><a href=\"/jiksan/about-services\">진료안내</a></li>\r\n");
      out.write("                     <li><a href=\"/jiksan/about-team\">의료진 소개</a></li>\r\n");
      out.write("                            <li><a href=\"/jiksan/contact-us\">오시는길</a></li>\r\n");
      out.write("                  </ol>\r\n");
      out.write("               </li>\r\n");
      out.write("               <li>\r\n");
      out.write("                  <div>당뇨클리닉</div>\r\n");
      out.write("                  <ol>\r\n");
      out.write("                     <li><a href=\"/jiksan/diabetes\" >당뇨병이란?</a></li>\r\n");
      out.write("                     <li><a href=\"/jiksan/diabetes-test\" >당뇨병 검사</a></li>\r\n");
      out.write("                     <li><a href=\"/jiksan/diabetes-diet\" >당뇨병과 식생활</a></li>\r\n");
      out.write("                     <li><a href=\"/jiksan/diabetes-exercise\" >당뇨병과 운동</a></li>\r\n");
      out.write("                     <li><a href=\"/jiksan/diabetes-complications\" >당뇨병 합병증</a></li>\r\n");
      out.write("                  </ol>\r\n");
      out.write("               </li>\r\n");
      out.write("               <li>\r\n");
      out.write("                  <div>건강정보</div>\r\n");
      out.write("                  <ol>\r\n");
      out.write("                     <li><a href=\"/jiksan/about-disease\">질환백과</a></li>\r\n");
      out.write("                     ");
      out.write("\r\n");
      out.write("                  </ol>   \r\n");
      out.write("               </li>\r\n");
      out.write("               <li>\r\n");
      out.write("                  <div>진료 예약 관리</div>\r\n");
      out.write("                  <ol>\r\n");
      out.write("                     <li><a href=\"#\">예약안내</a></li>\r\n");
      out.write("                     <li><a href=\"/jiksan/views/user/userReservation.html\">진료 예약하기</a></li>\r\n");
      out.write("                     ");
      out.write("\r\n");
      out.write("                  </ol>   \r\n");
      out.write("               </li>\r\n");
      out.write("               <li>\r\n");
      out.write("                  <div>커뮤니티 관리</div>\r\n");
      out.write("                  <ol>\r\n");
      out.write("                     <li><a href=\"/jiksan/views/notice/nlist\">공지사항</a></li>\r\n");
      out.write("                     <li><a href=\"/jiksan/views/faq/faqlist\">자주묻는 질문</a></li>\r\n");
      out.write("                     <li><a href=\"#\">Q&A 게시판</a></li>\r\n");
      out.write("                     ");
      out.write("\r\n");
      out.write("                  </ol>   \r\n");
      out.write("               </li>\r\n");
      out.write("               <li>\r\n");
      out.write("                  <div>회원 관리</div>\r\n");
      out.write("                  <ol>\r\n");
      out.write("                     <li><a href=\"#\">회원 리스트</a></li>\r\n");
      out.write("                     <li><a href=\"#\">#</a></li>\r\n");
      out.write("                     <li><a href=\"#\">#</a></li>\r\n");
      out.write("                  </ol>   \r\n");
      out.write("               </li>\r\n");
      out.write("            </ul>\r\n");
      out.write("         </div>\r\n");
      out.write("      </div>\r\n");
 } else { 
      out.write(" <!-- 환자가 로그인했다면 -->\r\n");
      out.write("\t<nav>\r\n");
      out.write("            <a href=\"/jiksan/logout\"><img src=\"/jiksan/resources/main_images/nav-icon01.png\" alt=\"LOGOUT\"><span>LOGOUT</span></a>\r\n");
      out.write("            <a href=\"/jiksan/views/user/userMyPage.jsp\"><img src=\"/jiksan/resources/main_images/nav-icon02.png\" alt=\"MY PAGE\"><span>MY PAGE</span></a>\r\n");
      out.write("            <a href=\"/jiksan/views/user/userReservation.html\"><img src=\"/jiksan/resources/main_images/nav-icon04.png\" alt=\"RESERVATION\"><span>RESERVATION</span></a>\r\n");
      out.write("            <a href=\"#n\" class=\"full-slide\">\r\n");
      out.write("               <div class=\"row\">\r\n");
      out.write("                  <div class=\"three col\">\r\n");
      out.write("                     <div class=\"hamburger\" id=\"hamburger-1\">\r\n");
      out.write("                        <span class=\"line\"></span>\r\n");
      out.write("                        <span class=\"line\"></span>\r\n");
      out.write("                        <span class=\"line\"></span>\r\n");
      out.write("                     </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("               </div>\r\n");
      out.write("               <span style=\"font-weight: 500; color: #74afc9;\">전체메뉴</span>\r\n");
      out.write("            </a>\r\n");
      out.write("         </nav>\r\n");
      out.write("</div>\r\n");
      out.write("            <div class=\"full-menu bg-white\">\r\n");
      out.write("         <div class=\"inner\">\r\n");
      out.write("            <ul class=\"full-list inner cf\">\r\n");
      out.write("               <li>\r\n");
      out.write("                  <div>병원안내</div>\r\n");
      out.write("                  <ol>\r\n");
      out.write("                     <li><a href=\"/jiksan/about-clinic\">병원안내</a></li>\r\n");
      out.write("                     <li><a href=\"/jiksan/about-services\">진료안내</a></li>\r\n");
      out.write("                     <li><a href=\"/jiksan/about-team\">의료진 소개</a></li>\r\n");
      out.write("                            <li><a href=\"/jiksan/contact-us\">오시는길</a></li>\r\n");
      out.write("                  </ol>\r\n");
      out.write("               </li>\r\n");
      out.write("               <li>\r\n");
      out.write("                  <div>당뇨클리닉</div>\r\n");
      out.write("                  <ol>\r\n");
      out.write("                     <li><a href=\"/jiksan/diabetes\" >당뇨병이란?</a></li>\r\n");
      out.write("                     <li><a href=\"/jiksan/diabetes-test\" >당뇨병 검사</a></li>\r\n");
      out.write("                     <li><a href=\"/jiksan/diabetes-diet\" >당뇨병과 식생활</a></li>\r\n");
      out.write("                     <li><a href=\"/jiksan/diabetes-exercise\" >당뇨병과 운동</a></li>\r\n");
      out.write("                     <li><a href=\"/jiksan/diabetes-complications\" >당뇨병 합병증</a></li>\r\n");
      out.write("                  </ol>\r\n");
      out.write("               </li>\r\n");
      out.write("               <li>\r\n");
      out.write("                  <div>건강정보</div>\r\n");
      out.write("                  <ol>\r\n");
      out.write("                     <li><a href=\"/jiksan/about-disease\">질환백과</a></li>\r\n");
      out.write("                     ");
      out.write("\r\n");
      out.write("                  </ol>   \r\n");
      out.write("               </li>\r\n");
      out.write("               <li>\r\n");
      out.write("                  <div>진료 예약</div>\r\n");
      out.write("                  <ol>\r\n");
      out.write("                     <li><a href=\"#\">예약안내</a></li>\r\n");
      out.write("                     <li><a href=\"/jiksan/views/user/userReservation.jsp\">진료 예약하기</a></li>\r\n");
      out.write("                     ");
      out.write("\r\n");
      out.write("                  </ol>   \r\n");
      out.write("               </li>\r\n");
      out.write("               <li>\r\n");
      out.write("                  <div>커뮤니티</div>\r\n");
      out.write("                  <ol>\r\n");
      out.write("                     <li><a href=\"/jiksan/views/notice/nlist\">공지사항</a></li>\r\n");
      out.write("                     <li><a href=\"/jiksan/views/faq/faqlist\">자주묻는 질문</a></li>\r\n");
      out.write("                     <li><a href=\"#\">Q&A 게시판</a></li>\r\n");
      out.write("                     ");
      out.write("\r\n");
      out.write("                  </ol>   \r\n");
      out.write("               </li>\r\n");
      out.write("            </ul>\r\n");
      out.write("         </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      ");
 } 
      out.write("\r\n");
      out.write("</section>\r\n");
      out.write("</header>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<hr>\r\n");
      out.write("<h1 align=\"center\">회원 정보 수정 페이지</h1>\r\n");
      out.write("<br>\r\n");
      out.write("<form action=\"/jiksan/uupdate\" method=\"post\">\r\n");
      out.write("<table id=\"outer\" align=\"center\" cellspacing=\"5\" cellpadding=\"0\">\r\n");
      out.write("<!-- <tr><th width=\"120\">회원구분</th>\r\n");
      out.write("\t\t<td><input type=\"radio\" name=\"user_lv\" value=\"1\" checked>일반</td>\r\n");
      out.write("\t</tr> -->\r\n");
      out.write("<tr><th width=\"120\">이 름</th>\r\n");
      out.write("\t<td><input type=\"text\" name=\"user_nm\" value=\"");
      out.print( user.getUserNm() );
      out.write("\" readonly></td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr><th width=\"120\">아이디</th>\r\n");
      out.write("\t<td><input type=\"text\" name=\"user_id\" value=\"");
      out.print( user.getUserId() );
      out.write("\" readonly></td></tr>\r\n");
      out.write("<tr>\t<th width=\"120\">비밀번호</th>\r\n");
      out.write("\t<td><input type=\"password\" name=\"user_pw\" id=\"user_pw1\" placeholder=\"영문 대소문자/숫자/특수문자 중 2가지 이상 조합, 8자~20자\">&nbsp;\r\n");
      out.write("\t</td></tr>\r\n");
      out.write("\t<tr><th width=\"120\">비밀번호 확인</th>\r\n");
      out.write("\t<td><input type=\"password\" id=\"user_pw2\"></td></tr>\r\n");
      out.write("<tr><th width=\"120\">휴대폰</th>\r\n");
      out.write("\t<td><input type=\"tel\" name=\"phone\" value=\"");
      out.print( user.getPhone() );
      out.write("\"></td></tr>\r\n");
      out.write("\r\n");
      out.write("<tr><th width=\"120\">주소</th>\r\n");
      out.write("\t<td><input type=\"text\" id=\"sample4_postcode\" name=\"address\" placeholder=\"우편번호\"> \r\n");
      out.write("\t<input type=\"button\" onclick=\"sample4_execDaumPostcode()\" value=\"우편번호 찾기\"> \r\n");
      out.write("\t<br>\r\n");
      out.write("\t<input type=\"text\" id=\"sample4_roadAddress\" name=\"address\" placeholder=\"도로명주소\" size=\"60\">\r\n");
      out.write("\t<br> <input type=\"hidden\" id=\"sample4_jibunAddress\" name=\"address\" placeholder=\"지번주소\" size=\"60\"> \r\n");
      out.write("\t<span id=\"guide\" style=\"color: #999; display: none\"></span> \r\n");
      out.write("\t<input type=\"text\" id=\"sample4_detailAddress\" name=\"address\" placeholder=\"상세주소\" size=\"60\"> <br>\r\n");
      out.write("\t<input type=\"hidden\" id=\"sample4_extraAddress\" name=\"address\" placeholder=\"참고항목\" size=\"60\">\r\n");
      out.write("    <input type=\"hidden\" id=\"sample4_engAddress\" name=\"address\" placeholder=\"영문주소\"></td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t\r\n");
      out.write("<tr><th width=\"120\">닉네임</th>\r\n");
      out.write("\t<td><input type=\"text\" name=\"nick_nm\" value=\"");
      out.print( user.getNickNm() );
      out.write("\" readonly></td>\r\n");
      out.write("\t\r\n");
      out.write("<tr><th width=\"120\">생년월일</th>\r\n");
      out.write("\t<td><input type=\"text\" name=\"birthday\" value=\"");
      out.print( user.getBirthday() );
      out.write("\" readonly></td>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<tr><th width=\"120\">성 별</th>\r\n");
      out.write("\t<td>\r\n");
      out.write("\t");
 if(user.getGender().equals("M")){ 
      out.write("\r\n");
      out.write("\t\t<input type=\"radio\" name=\"gender\" value=\"M\" checked readonly> 남자 &nbsp; \r\n");
      out.write("\t\t<input type=\"radio\" name=\"gender\" value=\"F\" readonly> 여자\r\n");
      out.write("\t");
 }else{ 
      out.write("\r\n");
      out.write("\t\t<input type=\"radio\" name=\"gender\" value=\"M\" readonly> 남자 &nbsp; \r\n");
      out.write("\t\t<input type=\"radio\" name=\"gender\" value=\"F\" checked readonly> 여자\r\n");
      out.write("\t");
 } 
      out.write("\r\n");
      out.write("\t</td></tr>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<tr><th width=\"120\" colspan=\"2\">\r\n");
      out.write("\t<input type=\"button\" value=\"탈퇴하기\" onclick=\"location.href=''\"> &nbsp; \r\n");
      out.write("\t<input type=\"submit\" value=\"수정하기\">\r\n");
      out.write("</th></tr>\r\n");
      out.write("</table>\r\n");
      out.write("</form>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<hr>\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("footer {\r\n");
      out.write("   background:#3e4247;\r\n");
      out.write("   text-align : center;\r\n");
      out.write("   width : 100%;\r\n");
      out.write("   height : 10%;\r\n");
      out.write("   color: #d1d1d1;\r\n");
      out.write("   font-size : 0.8em;\r\n");
      out.write("   padding-top : 2%;   \r\n");
      out.write("   padding-bottom : 2%;   \r\n");
      out.write("   line-height:1;\r\n");
      out.write("}\r\n");
      out.write("footer div h3 {\r\n");
      out.write("   color: #fff;\r\n");
      out.write("   font-size : 1.2em;\r\n");
      out.write("   font-weight : none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".footer_btn_list li {\r\n");
      out.write(" float: auto; overflow: hidden;\r\n");
      out.write(" padding-right: 10px;\r\n");
      out.write(" display:inline;\r\n");
      out.write(" line-height:2;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#copyright, .footer_btn_list, address{\r\n");
      out.write("   color: #9AA0A6 /* #80868B */\r\n");
      out.write("} \r\n");
      out.write("hr { clear : both; }\r\n");
      out.write("</style>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("   //개인정보처리방침\r\n");
      out.write("   function OpenMemberPrivate() { // \"개인정보처리방침\" 만들기? 가져오기\r\n");
      out.write("      window.open(\r\n");
      out.write("                  \"/jiksan/resources/js/개인정보처리방침.asp\",\r\n");
      out.write("                  \"MemberPrivate\",\r\n");
      out.write("                  \"toolbar=0, left=100, top=50, location=0, directories=0, status=0, menubar=0, scrollbars=1, resizable=0, copyhistory=0, width=600 ,height=600\");\r\n");
      out.write("   }\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<footer>\r\n");
      out.write("<div>\r\n");
      out.write("            <h3>직산 가정의학과 의원 Jiksan Family Medicine Clinic</h3><br>\r\n");
      out.write("            <address>충남 천안시 서북구 직산읍 직산로 31 직산농협 2층 &nbsp;&nbsp;&nbsp;&nbsp; (041) 583-8500\r\n");
      out.write("            </address>\r\n");
      out.write("            <br> <br>\r\n");
      out.write("            <p>\r\n");
      out.write("               평일 08:30 ~ 18:00 &nbsp;&nbsp;&nbsp;&nbsp; 토요일 09:00 ~ 13:00\r\n");
      out.write("               &nbsp;&nbsp;&nbsp;&nbsp; 점심시간 13:00 ~ 14:00\r\n");
      out.write("               &nbsp;&nbsp;&nbsp;&nbsp; 화요일 야간진료 21:00 까지 &nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("               <i>일요일/공휴일은 휴무입니다.</i>\r\n");
      out.write("            </p>\r\n");
      out.write("            <br>\r\n");
      out.write("            <br>\r\n");
      out.write("            <label id=\"copyright\">Copyright ⓒ 2020 by Jiksan Family Medicine Clinic. All rights reserved.</label>\r\n");
      out.write("            <br>\r\n");
      out.write("         </div>\r\n");
      out.write("            <ul class=\"footer_btn_list\">\r\n");
      out.write("               <li><a href=\"#\" onclick=\"OpenMemberPrivate();\" style=\"cursor: pointer;\">개인정보처리방침</a></li>\r\n");
      out.write("               <li> | </li>\r\n");
      out.write("               <li><a href=\"#\">이용약관</a></li>\r\n");
      out.write("               <li> | </li>\r\n");
      out.write("               <li><a href=\"/jiksan/contact-us\">찾아오시는길</a></li>         ");
      out.write("\r\n");
      out.write("            </ul>\r\n");
      out.write("</footer>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
